modules/animal-management/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>Stores information pertaining to an animal.</description>
    <label>Animal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Animal Internal Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of the Animal.</description>
    <inlineHelpText>Please enter the birth date of the animal. This field can be blank if the birth date is unknown.</inlineHelpText>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Stores information to animal&apos;s appointments</description>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Animal the booking is for</description>
    <inlineHelpText>Please select the animal for whom this booking is for</inlineHelpText>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

modules/booking-management/objects/Booking__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Appointment Date</description>
    <inlineHelpText>Please enter the date of the appointment</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of appointment</description>
    <inlineHelpText>Please select the type of appointment.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vet</fullName>
            </value>
            <value>
                <fullName>Grooming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

modules/booking-management/classes/BookingHandler.cls
/**
 * @description Handles the different database events happening on the
 *              Animal__c SObject.
 */
public with sharing class BookingHandler implements AnimalTriggerHandler {

    /**
     * @description Automatically creates a new booking when an animal
     *              record is inserted in the database.
     *              The date of the booking is defined by the age of the
     *              animal that is being inserted.
     * @param animalsById Map of the animals records being inserted in
     *                    the database
     */
    public void handle(Map<Id, Animal__c> animalsById) {
        List<Booking__c> newBookings = new List<Booking__c>();
        for (Animal__c animal : animalsById.values()) {
            Booking__c newBooking = new Booking__c();
            newBooking.Animal__c = animal.Id;
            newBooking.Type__c = 'Vet';
            if (animal.BirthDate__c.monthsBetween(Date.TODAY()) < 6){
                newBooking.Date__c = animal.BirthDate__c.addMonths(6);
            } else {
                newBooking.Date__c = (Date.TODAY()).addMonths(6);
            }
            newBookings.add(newBooking);
        }

        insert newBookings;
    }
}