modules/animal-management/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>Stores information pertaining to an animal.</description>
    <label>Animal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Animal Internal Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

modules/animal-management/objects/Animal__c/fields/AnimalName__c.field-meta.xml
<CustomField>
    <fullName>AnimalName__c</fullName>
    <description>Please enter the name of the animal.
If the animal does not have a name, please leave blank.
Once the animal has been adopted, please update this information with the name provided by the owner.</description>
    <inlineHelpText>Name of the Animal</inlineHelpText>
    <label>Animal Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>Birth Date of the Animal.</description>
    <inlineHelpText>Please enter the birth date of the animal. This field can be blank if the birth date is unknown.</inlineHelpText>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

modules/product-management/classes/AbstractAnimal.cls
public abstract class AbstractAnimal implements Animal {
    protected String name;
    protected String species;
    protected Date birthDate;

    public AbstractAnimal(Animal__c animalRecord) {

        if (animalRecord == null) {
            // animalRecord is a mandatory parameter
            throw new IllegalArgumentException('animal parameter cannot be null.');
        }

        this.name = animalRecord.AnimalName__c;
        this.birthDate = animalRecord.BirthDate__c;
    }

    public String getName() {
        return this.name;
    }

    public Date getBirthDate() {
        return this.birthDate;
    }

    public String getPersonalisedProduct() {
        if (isBornRecently()) {
            return 'Flowers - Congratulations';
        }

        return '';
    }

    private Boolean isBornRecently() {
        if (this.birthDate.monthsBetween(Date.today()) > 6) {
            return false;
        }

        return true;
    }
}