modules/animal-management/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <description>Stores information pertaining to an animal.</description>
    <label>Animal</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Animal Internal Identifier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

modules/animal-management/objects/Animal__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bird</fullName>
            </value>
            <value>
                <fullName>Cat</fullName>
            </value>
            <value>
                <fullName>Dog</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Reptile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

modules/product-management/classes/AnimalFactory.cls
public class AnimalFactory {
    public static Animal createAnimal(Animal__c animalRecord) {
        Animal returnedAnimal;
        switch on animalRecord.Species__c {
            when 'Dog' {
                returnedAnimal = new Dog(animalRecord);
            } when 'Cat' {
                returnedAnimal = new Cat(animalRecord);
            } when 'Bird' {
                returnedAnimal = new Bird(animalRecord);
            } when else {
                returnedAnimal = new DefaultAnimal(animalRecord);
            }
        }

        return returnedAnimal;
    }
}